# Site Settings
title: 30 Days of Code
email: jgsimmerman@gmail.com
description: >
  30 Day Deep Dive into Coding.
baseurl: "/30days"
url: "http://ibws.com/30days/"
twitter_username: jgsimmerman
github_username:  jgsimmerman
# Build Settings
sass:
  sass_dir: _sass
  style: compressed
include: ['_pages']
kramdown:
  input: GFM

#Disqus post comments
disqus_shortname: jacobsimmerman
